### PR TITLE
Upgraded Baileys Version ✅⬆⬆

### PR DESCRIPTION
**Pull request by toxic-devil**

### CODE REVIEW

**Comment by farhan-dqz** [comment]
> QR CODE BUG FIXED : new version 3.5.2 ✅⬆⬆⬆
> 
> const Message To Farhan : "Njan oru organization invite ittittund nokk email nokk" 🤣🤣

Haa..Nee insta keri nokk

**Comment by farhan-dqz** [comment]
> QR CODE BUG FIXED : new version 3.5.2 ✅⬆⬆⬆
> 
> const Message To Farhan : "Njan oru organization invite ittittund nokk email nokk" 🤣🤣

Daa ath 404 error anu. git dlt akyoo

**Comment by TOXIC-DEVIL** [comment]
> > QR CODE BUG FIXED : new version 3.5.2 ✅⬆⬆⬆
> > const Message To Farhan : "Njan oru organization invite ittittund nokk email nokk" 🤣🤣
> 
> Daa ath 404 error anu. git dlt akyoo

**Comment by TOXIC-DEVIL** [comment]
> > QR CODE BUG FIXED : new version 3.5.2 ✅⬆⬆⬆
> > const Message To Farhan : "Njan oru organization invite ittittund nokk email nokk" 🤣🤣
> 
> Haa..Nee insta keri nokk

Okay ✅️

**Comment by TOXIC-DEVIL** [comment]
> > QR CODE BUG FIXED : new version 3.5.2 ✅⬆⬆⬆
> > const Message To Farhan : "Njan oru organization invite ittittund nokk email nokk" 🤣🤣
> 
> Haa..Nee insta keri nokk

Reply thannu ✅️

**Pull request merged**
