### PR TITLE
New Announcement System ✅️

### PR DESCRIPTION
**Pull request by toxic-devil**

### CODE REVIEW

**Comment by farhan-dqz** [comment]
> Ee Pull Accept Cheyyuvanel ;
> Ni aa Announcement ezhuthiyekkunne daily/mothly/event-based-dates == mattikkondirikkumello alle 😂✅️

nee enthada Whtspp install cheyyathe.. Ninne ethil contact cheyyan kayya🤕

**Comment by TOXIC-DEVIL** [comment]
> > Ee Pull Accept Cheyyuvanel ;
> > Ni aa Announcement ezhuthiyekkunne daily/mothly/event-based-dates == mattikkondirikkumello alle 😂✅️
> 
> nee enthada Whtspp install cheyyathe.. Ninne ethil contact cheyyan kayya🤕

IG id thaa 😂

**Comment by TOXIC-DEVIL** [comment]
Pull Req Accept keroo ✅️

**Comment by farhan-dqz** [comment]
> > > Ee Pull Accept Cheyyuvanel ;
> > > Ni aa Announcement ezhuthiyekkunne daily/mothly/event-based-dates == mattikkondirikkumello alle 😂✅️
> > 
> > 
> > nee enthada Whtspp install cheyyathe.. Ninne ethil contact cheyyan kayya🤕
> 
> image
> 
> IG id thaa 😂 Njan Ellam Parayam 😂

Farhan_dqz.ecx

**Comment by farhan-dqz** [comment]
> > > > Ee Pull Accept Cheyyuvanel ;
> > > > Ni aa Announcement ezhuthiyekkunne daily/mothly/event-based-dates == mattikkondirikkumello alle 😂✅️
> > > 
> > > 
> > > nee enthada Whtspp install cheyyathe.. Ninne ethil contact cheyyan kayya🤕
> > 
> > 
> > image
> > IG id thaa 😂 Njan Ellam Parayam 😂
> 
> Farhan_dqz.ecx

Y drafted. njn marann poyatha

**Comment by TOXIC-DEVIL** [comment]
> > > > > Ee Pull Accept Cheyyuvanel ;
> > > > > Ni aa Announcement ezhuthiyekkunne daily/mothly/event-based-dates == mattikkondirikkumello alle 😂✅️
> > > > 
> > > > 
> > > > nee enthada Whtspp install cheyyathe.. Ninne ethil contact cheyyan kayya🤕
> > > 
> > > 
> > > image
> > > IG id thaa 😂 Njan Ellam Parayam 😂
> > 
> > 
> > Farhan_dqz.ecx
> 
> Y drafted. njn marann poyatha

Okay ✅️

**Comment by toxic-devil** [comment]
> > > > Ee Pull Accept Cheyyuvanel ;
> > > > Ni aa Announcement ezhuthiyekkunne daily/mothly/event-based-dates == mattikkondirikkumello alle 😂✅️
> > > 
> > > 
> > > nee enthada Whtspp install cheyyathe.. Ninne ethil contact cheyyan kayya🤕
> > 
> > 
> > image
> > IG id thaa 😂 Njan Ellam Parayam 😂
> 
> Farhan_dqz.ecx

Njan msg ittittund nokk 😂
Ee pull accept cheyyenda ketto @farhan-dqz njan ith modifie cheythitt vere pull idam ( After modifing a 😂) @farhan-dqz @farhan-dqz @farhan-dqz @farhan-dqz

**Pull request closed without merging**
